function h(){

    await{ 
            call(
                x, 
                defer(var x, y, z), 
                gen(i)
            );
    }
    await{ 
            call(
                x, 
                defer(x, y[i], z(x[i])), 
                gen(i)
            );
    }
    await{ 
            call(
                x, 
                defer(good), 
                // defer(bad), 
                gen(i)
            );
    }
 
}
